
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config

    labels:
      caddy.email: eric.busboom@jointheleague.org

  whoami:
    image: traefik/whoami
    networks:
      - caddy

    labels:
      caddy: whoami.jtlapp.net
      caddy.reverse_proxy: "{{upstreams 80}}"

  hello:
    image: crccheck/hello-world
    networks:
      - caddy

    labels:
      caddy: hello.jtlapp.net
      caddy.reverse_proxy: "{{upstreams 8000}}"

    ports:
      - 8000:8000


volumes:
  caddy_data: {}
  caddy_config: {}


networks:
  caddy:
    external: true