- name: Manage Docker Swarm Nodes
  hosts: swarm_nodes
  gather_facts: false
  become: true # Ensure we have root privileges for hostname changes
  tasks:
    - name: Ensure pip3 is installed
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Set the hostname
      hostname:
        name: "{{ hostname }}"

    - name: Ensure node is in the correct role
      community.docker.docker_node:
        hostname: "{{ hostname }}"
        role: "{{ role }}"

    - name: Set ingress label if ingress is true
      community.docker.docker_node:
        hostname: "{{ hostname }}"
        labels:
          ingress: "true"
      when: ingress | bool

    - name: Copy private SSH key
      copy:
        src: id_rsa
        dest: /root/.ssh/id_rsa
        mode: "0600"
      become: true

    - name: Copy public SSH key
      copy:
        src: id_rsa.pub
        dest: /root/.ssh/id_rsa.pub
        mode: "0644"
      become: true

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'id_rsa.pub') }}"
      become: true

    - name: Configure SSH to disable strict host key checking
      lineinfile:
        path: /root/.ssh/config
        state: present
        create: yes
        line: |
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            LogLevel QUIET
      become: true
