services:
  cs-spawner:
    image: codeserv
    container_name: codeserv
    build:
      context: .
      dockerfile: Dockerfile

    # These labels set up the domain name in the Caddy proxy
    labels:
      caddy: code.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 8000}}"

    environment:
      key: value

    volumes:
      - app-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/student_repos:/mnt/student_repos

    # Expose Flask app on host port 8090
    ports:
      - "8090:8000"

    networks: # Must exist to recieve traffic from Caddy
      - caddy
      - jtlctl

networks:
  caddy:
    external: true
  jtlctl:

volumes:
  app-data:

