services:

  cron:
    build:
      context: cron-app
    image: jtl-cron # CHANGE to an image name specific to this project

    volumes:
      - app-data:/app/data

    restart: unless-stopped

  flask:
    image: jtl-flask # CHANGE to an image name specific to this project
    build:
      context: flask-app

    # These labels set up the domain name in the Caddy proxy
    labels:
      caddy: example-flask.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 8000}}"

    volumes:
      - app-data:/app
      - /var/run/docker.sock:/var/run/docker.sock

     # Expose Flask app on host port 8090
    ports:
      - "8090:8000"

    networks: # Must exist to recieve traffic from Caddy
      - caddy


networks:
  caddy:
    external: true


volumes:
  app-data:

