services:

  cron:
    build:
      context: cron-app
    image: jtl-cron # CHANGE to an image name specific to this project

    volumes:
      - app-data:/opt/data

    restart: unless-stopped

  flask:
    image: jtl-flask # CHANGE to an image name specific to this project
    build:
      context: flask-app

    # These labels set up the domain name in the Caddy proxy
    labels:
      caddy: example-flask.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 8000}}"

    volumes:
      - app-data:/opt/data

     # Expose Flask app on host port 8090
    ports:
      - "8090:8000"

    networks: # Must exist to recieve traffic from Caddy
      - caddy

  nginx:
    build:
      context: nginx
    image: jtl-nginx # CHANGE to an image name specific to this project

    volumes:
      - app-data:/opt/data

    labels:
      caddy: example-nginx.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 80}}"
      
      caddy.basic_auth: "*"
      caddy.basic_auth.code: ${PASSWORD}

    restart: unless-stopped

    # Expose NGINX server on host port 8091
    ports:
      - "8091:80"

    networks:
      - caddy


networks:
  caddy:
    external: true


volumes:
  app-data:

