services:
  codeserv:
    image: codeserv

    build:
      context: ..
      dockerfile: docker/Dockerfile

    deploy:
      replicas: 1
      labels:
        caddy: code.jointheleague.org
        caddy.reverse_proxy: "{{upstreams 8000}}"
      placement:
        constraints:
          - node.role == manager
   
    environment:
      JTL_DEPLOYMENT: "prod"

    volumes:
      - app-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      #- /mnt/student_repos:/mnt/student_repos

    # Expose Flask app on host port 8090
    ports:
      - "5000:8000"


    networks: # Must exist to recieve traffic from Caddy
      - caddy
      - jtlctl



networks:
  caddy:
    external: true
  jtlctl: # docker network create --driver overlay --attachable jtlctl

volumes:
  app-data:
