
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

    labels:
      caddy.email: eric.busboom@jointheleague.org

  whoami:
    image: traefik/whoami
    networks:
      - caddy

    labels:
      caddy: whoami.amazingprogrammers.org
      caddy.reverse_proxy: "{{upstreams 80}}"

  hello:
    image: crccheck/hello-world
    networks:
      - caddy

    labels:
      caddy: hello.amazingprogrammers.org
      caddy.reverse_proxy: "{{upstreams 8000}}"

    ports:
      - 8000:8000


volumes:
  caddy_data: {}

# For swarm, need to create this network with:
# docker network create --driver overlay --attachable caddy
  
networks:
  caddy:
    external: true