version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: codeserv-postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d codeserver -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7
    container_name: codeserv-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: codeserver
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: codeserv-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jointheleague.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongo-express:
    image: mongo-express:latest
    container_name: codeserv-mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  postgres-data:
  mongo-data:
  pgadmin-data:
