"""Add password and syllabus 

Revision ID: 974a6216fb41
Revises: 
Create Date: 2025-02-26 12:01:36.728551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974a6216fb41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    with op.batch_alter_table('host_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syllabus_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_images', schema=None) as batch_op:
        batch_op.drop_column('syllabus_path')

    with op.batch_alter_table('code_host', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
