""".

Revision ID: d1c619edda23
Revises: e3a32cf79e0e
Create Date: 2025-03-16 11:10:49.243321

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d1c619edda23"
down_revision = "e3a32cf79e0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("running", sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column("running_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("stops_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_column("data")
        batch_op.drop_column("stops_at")
        batch_op.drop_column("running_at")
        batch_op.drop_column("running")

    # ### end Alembic commands ###
